### ISSUE TITLE
Webpacker doesn't know how to handle aunty's command shortcuts / options

### ISSUE THREAD

**Issue by colingourlay** [abcnews/webpacker#1]
Aunty aliases `b` to `build` and `s` to `serve`, but whenever either of these shortcuts are used with webpacker projects, the assumption is always `build`.

Aunty also allows the `-d` or `--debug` option on either of the above commands to differentiate between a development build and a production build. I wonder if there's a way to let those inform webpack.

**Comment by nathanhoad** [comment]
I've added support for the `s` shortcut (`b` already defaults to build).

Webpacker uses `NODE_ENV` to work out if it should sourcemap/uglify the output so the `--debug` option isn't needed.
